title: George Sovetov
description: Blog on various aspects of software engineering
google_analytics: G-1WBXB55FDD
remote_theme: jekyll/slate@a185c0dde883863779be4856421ba0b2390f44a4
plugins:
- jekyll-remote-theme